##############################################
# Spring boot properties
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
##############################################
spring:
  output:
    ansi:
      enabled: always
  profiles:
    active:
  threads:
    virtual:
      enabled: true
  mvc:
    problemdetails:
      enabled: false

#############################
logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%-5p}) [%-11t] %clr([%-26logger{25}]){cyan} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:%5p} [%t] %logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  file:
    name: .log/hibachi.log
  logback:
    rollingpolicy:
      max-history: 3

#############################
management:
  endpoints:
    web:
      exposure:
        include: health,info,shutdown,env,heapdump,threaddump,metrics,prometheus,scheduledtasks
      base-path: /api/actuator

#############################
server:
  port: 9090
  error:
    whitelabel:
      enabled: false
    path: /error
    include-exception: true
    include-message: always
    include-stacktrace: always
    include-binding-errors: always

